### ISSUE TITLE
Handle unavailable tentacles.

### ISSUE THREAD

**Issue by kodemaniak** [logtopus/logtopus#8]
Currently the request will fail. Since in larger deployments we can expect this to happen regularly, I assume the request should be run against the available tentacles with some kind of info about missing tentacles being added to the JSON or response headers? (@matipp)

**Comment by niveau0** [comment]
Quite difficult, I'm unsure if this should be part of the json of the log stream (becomes more and more complex), maybe an extra resource? Depends how the outcome is visualized

**Comment by kodemaniak** [comment]
We will provide additional log lines at the beginning at the start and end of the log stream on ERROR log level for each failing tentacle.

**Comment by kodemaniak** [comment]
Closed by 880042bef51a13021bd72f80b076e09a0956065b.
